package com.efit.hrms.repo;

import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.efit.hrms.entity.AttendanceProcessVO;

@Repository
public interface AttendanceProcessRepo extends JpaRepository<AttendanceProcessVO, Long>{

//	
//	@Query(nativeQuery = true, value = 
//		    "WITH RECURSIVE date_series AS (\r\n"
//		    + "    SELECT DATE(?1) AS dt\r\n"
//		    + "    UNION ALL\r\n"
//		    + "    SELECT DATE_ADD(dt, INTERVAL 1 DAY)\r\n"
//		    + "    FROM date_series\r\n"
//		    + "    WHERE dt < DATE(?2)\r\n"
//		    + "),\r\n"
//		    + "weekoffs AS (\r\n"
//		    + "    SELECT ds.dt AS weekoffdate\r\n"
//		    + "    FROM date_series ds\r\n"
//		    + "    JOIN companyweekoff cw\r\n"
//		    + "      ON cw.companyid = ?3\r\n"
//		    + "     AND UPPER(DAYNAME(ds.dt)) = UPPER(cw.weekoffdays)\r\n"
//		    + "),\r\n"
//		    + "holidays_cte AS (\r\n"
//		    + "    SELECT holidaydate\r\n"
//		    + "    FROM holidays\r\n"
//		    + "    WHERE orgid = ?3\r\n"
//		    + "      AND holidaydate BETWEEN ?1 AND DATE_SUB(?2, INTERVAL 1 DAY)\r\n"
//		    + "),\r\n"
//		    + "emp_base AS (\r\n"
//		    + "    SELECT DISTINCT lb.employeecode, lb.employee\r\n"
//		    + "    FROM leavebalance lb\r\n"
//		    + "    JOIN employee e ON lb.employeecode = e.employeecode\r\n"
//		    + "    WHERE lb.orgid = ?3\r\n"
//		    + "      AND (?4 = 'ALL' OR e.department = ?4)\r\n"
//		    + "      AND (?5 = 'ALL' OR e.branch = ?5)\r\n"
//		    + "),\r\n"
//		    + "company_cte AS (\r\n"
//		    + "    SELECT * FROM company WHERE companyid = ?3\r\n"
//		    + "),\r\n"
//		    + "date_series_with_emp AS (\r\n"
//		    + "    SELECT eb.employeecode, ds.dt AS checkindate\r\n"
//		    + "    FROM emp_base eb\r\n"
//		    + "    JOIN date_series ds\r\n"
//		    + "),\r\n"
//		    + "missing_days AS (\r\n"
//		    + "    SELECT e.employeecode, e.checkindate\r\n"
//		    + "    FROM date_series_with_emp e\r\n"
//		    + "    LEFT JOIN company_cte c ON 1=1\r\n"
//		    + "    LEFT JOIN attendanceprocess a\r\n"
//		    + "        ON a.empcode = e.employeecode\r\n"
//		    + "       AND a.checkindate = e.checkindate\r\n"
//		    + "       AND FIND_IN_SET(a.attendancemode, c.attendancemode)\r\n"
//		    + "       AND a.orgid = ?3\r\n"
//		    + "    LEFT JOIN approvalleaves al\r\n"
//		    + "        ON al.employeecode = e.employeecode\r\n"
//		    + "       AND al.leavedate = e.checkindate\r\n"
//		    + "       AND al.orgid = ?3\r\n"
//		    + "    LEFT JOIN holidays_cte h ON h.holidaydate = e.checkindate\r\n"
//		    + "    LEFT JOIN weekoffs w ON w.weekoffdate = e.checkindate\r\n"
//		    + "    WHERE a.empcode IS NULL\r\n"
//		    + "      AND al.leavedate IS NULL\r\n"
//		    + "      AND h.holidaydate IS NULL\r\n"
//		    + "      AND w.weekoffdate IS NULL\r\n"
//		    + "),\r\n"
//		    + "lop_days_final AS (\r\n"
//		    + "    SELECT employeecode, COUNT(*) AS lop\r\n"
//		    + "    FROM (\r\n"
//		    + "        SELECT employeecode\r\n"
//		    + "        FROM approvalleaves\r\n"
//		    + "        WHERE leavetype = 'LOSS OF PAY'\r\n"
//		    + "          AND leavedate BETWEEN ?1 AND DATE_SUB(?2, INTERVAL 1 DAY)\r\n"
//		    + "          AND orgid = ?3\r\n"
//		    + "        UNION ALL\r\n"
//		    + "        SELECT employeecode\r\n"
//		    + "        FROM missing_days\r\n"
//		    + "    ) all_lop\r\n"
//		    + "    GROUP BY employeecode\r\n"
//		    + "),\r\n"
//		    + "absent_days AS (\r\n"
//		    + "    SELECT employeecode, COUNT(*) AS absent\r\n"
//		    + "    FROM missing_days\r\n"
//		    + "    GROUP BY employeecode\r\n"
//		    + "),\r\n"
//		    + "present_days AS (\r\n"
//		    + "    SELECT empcode, SUM(present_day_value) AS presentdays\r\n"
//		    + "    FROM (\r\n"
//		    + "        SELECT\r\n"
//		    + "            c.empcode,\r\n"
//		    + "            c.checkindate,\r\n"
//		    + "            CASE\r\n"
//		    + "                WHEN MIN(CASE WHEN LOWER(c.status) = 'in' THEN c.entrytime END) IS NOT NULL\r\n"
//		    + "                  AND MAX(CASE WHEN LOWER(c.status) = 'out' THEN c.entrytime END) IS NOT NULL\r\n"
//		    + "                  AND TIMESTAMPDIFF(MINUTE,\r\n"
//		    + "                        STR_TO_DATE(MIN(CASE WHEN LOWER(c.status) = 'in' THEN c.entrytime END), '%H:%i:%s'),\r\n"
//		    + "                        STR_TO_DATE(MAX(CASE WHEN LOWER(c.status) = 'out' THEN c.entrytime END), '%H:%i:%s')\r\n"
//		    + "                    ) >= TIMESTAMPDIFF(MINUTE,\r\n"
//		    + "                        STR_TO_DATE(CONCAT(s.intime, ':00'), '%H:%i:%s'),\r\n"
//		    + "                        STR_TO_DATE(CONCAT(s.outtime, ':00'), '%H:%i:%s')\r\n"
//		    + "                    ) - 120 THEN 1\r\n"
//		    + "                WHEN MIN(CASE WHEN LOWER(c.status) = 'in' THEN c.entrytime END) IS NOT NULL\r\n"
//		    + "                  AND MAX(CASE WHEN LOWER(c.status) = 'out' THEN c.entrytime END) IS NOT NULL\r\n"
//		    + "                  AND TIMESTAMPDIFF(MINUTE,\r\n"
//		    + "                        STR_TO_DATE(MIN(CASE WHEN LOWER(c.status) = 'in' THEN c.entrytime END), '%H:%i:%s'),\r\n"
//		    + "                        STR_TO_DATE(MAX(CASE WHEN LOWER(c.status) = 'out' THEN c.entrytime END), '%H:%i:%s')\r\n"
//		    + "                    ) >= (TIMESTAMPDIFF(MINUTE,\r\n"
//		    + "                        STR_TO_DATE(CONCAT(s.intime, ':00'), '%H:%i:%s'),\r\n"
//		    + "                        STR_TO_DATE(CONCAT(s.outtime, ':00'), '%H:%i:%s')\r\n"
//		    + "                    ) / 2) - 90 THEN 0.5\r\n"
//		    + "                ELSE 0\r\n"
//		    + "            END AS present_day_value\r\n"
//		    + "        FROM attendanceprocess c\r\n"
//		    + "        JOIN company_cte cc ON 1=1\r\n"
//		    + "        JOIN shiftassigndetails s\r\n"
//		    + "          ON c.empcode = s.employeecode\r\n"
//		    + "         AND DATE(s.effectivefrom) <= c.checkindate\r\n"
//		    + "         AND DATE(s.effectiveto) >= c.checkindate\r\n"
//		    + "        WHERE FIND_IN_SET(c.attendancemode, cc.attendancemode)\r\n"
//		    + "          AND c.orgid = ?3\r\n"
//		    + "          AND c.checkindate BETWEEN ?1 AND DATE_SUB(?2, INTERVAL 1 DAY)\r\n"
//		    + "        GROUP BY c.empcode, c.checkindate, s.intime, s.outtime\r\n"
//		    + "    ) x\r\n"
//		    + "    GROUP BY empcode\r\n"
//		    + "),\r\n"
//		    + "month_info AS (\r\n"
//		    + "    SELECT COUNT(*) AS totaldays FROM date_series\r\n"
//		    + "),\r\n"
//		    + "leave_days AS (\r\n"
//		    + "    SELECT employeecode, COUNT(*) AS leaves\r\n"
//		    + "    FROM approvalleaves\r\n"
//		    + "    WHERE leavedate BETWEEN ?1 AND DATE_SUB(?2, INTERVAL 1 DAY)\r\n"
//		    + "      AND orgid = ?3\r\n"
//		    + "    GROUP BY employeecode\r\n"
//		    + "),\r\n"
//		    + "holiday_count AS (\r\n"
//		    + "    SELECT COUNT(*) AS holidays FROM holidays_cte\r\n"
//		    + "),\r\n"
//		    + "weekoff_count AS (\r\n"
//		    + "    SELECT COUNT(*) AS weekoff FROM weekoffs\r\n"
//		    + ")\r\n"
//		    + "\r\n"
//		    + "SELECT\r\n"
//		    + "    eb.employee AS name,\r\n"
//		    + "    eb.employeecode AS code,\r\n"
//		    + "    e.branch,\r\n"
//		    + "    e.department,\r\n"
//		    + "    MONTH(DATE(?1)) AS month,\r\n"
//		    + "    YEAR(DATE(?1)) AS year,\r\n"
//		    + "    mi.totaldays,\r\n"
//		    + "    hc.holidays,\r\n"
//		    + "    wc.weekoff AS weekoff,\r\n"
//		    + "    COALESCE(ld.leaves, 0) AS leaves,\r\n"
//		    + "    COALESCE(abs.absent, 0) AS absent,\r\n"
//		    + "    COALESCE(lop.lop, 0) AS lop,\r\n"
//		    + "    COALESCE(pd.presentdays, 0) AS presentdays,\r\n"
//		    + "    CASE \r\n"
//		    + "        WHEN COALESCE(pd.presentdays, 0) > 0 THEN mi.totaldays - COALESCE(lop.lop, 0) \r\n"
//		    + "        ELSE 0\r\n"
//		    + "    END AS salarydays\r\n"
//		    + "FROM emp_base eb\r\n"
//		    + "JOIN employee e ON eb.employeecode = e.employeecode\r\n"
//		    + "CROSS JOIN month_info mi\r\n"
//		    + "CROSS JOIN holiday_count hc\r\n"
//		    + "CROSS JOIN weekoff_count wc\r\n"
//		    + "LEFT JOIN leave_days ld ON eb.employeecode = ld.employeecode\r\n"
//		    + "LEFT JOIN lop_days_final lop ON eb.employeecode = lop.employeecode\r\n"
//		    + "LEFT JOIN present_days pd ON eb.employeecode = pd.empcode\r\n"
//		    + "LEFT JOIN absent_days abs ON eb.employeecode = abs.employeecode\r\n"
//		    + "ORDER BY eb.employeecode;\r\n"
//		    + ""
//		)
//	Set<Object[]> getLeaveDetailsForAttendanceProcess(String fromDate, String toDate, Long orgId, String department,
//			String branch);
//
//	
	
	
	
	
	@Query(nativeQuery = true, value = 
		    "WITH RECURSIVE date_series AS (\r\n"
		    + "    SELECT DATE(?1) AS dt\r\n"
		    + "    UNION ALL\r\n"
		    + "    SELECT DATE_ADD(dt, INTERVAL 1 DAY)\r\n"
		    + "    FROM date_series\r\n"
		    + "    WHERE dt < DATE(?2)\r\n"
		    + "),\r\n"
		    + "weekoffs AS (\r\n"
		    + "    SELECT ds.dt AS weekoffdate\r\n"
		    + "    FROM date_series ds\r\n"
		    + "    JOIN companyweekoff cw\r\n"
		    + "      ON cw.companyid = ?3\r\n"
		    + "     AND UPPER(DAYNAME(ds.dt)) = UPPER(cw.weekoffdays)\r\n"
		    + "),\r\n"
		    + "holidays_cte AS (\r\n"
		    + "    SELECT holidaydate\r\n"
		    + "    FROM holidays\r\n"
		    + "    WHERE orgid = ?3\r\n"
		    + "      AND holidaydate BETWEEN ?1 AND ?2\r\n"
		    + "),\r\n"
		    + "emp_base AS (\r\n"
		    + "    SELECT DISTINCT lb.employeecode, lb.employee\r\n"
		    + "    FROM leavebalance lb\r\n"
		    + "    JOIN employee e ON lb.employeecode = e.employeecode\r\n"
		    + "    WHERE lb.orgid = ?3\r\n"
		    + "),\r\n"
		    + "company_cte AS (\r\n"
		    + "    SELECT * FROM company WHERE companyid = ?3\r\n"
		    + "),\r\n"
		    + "date_series_with_emp AS (\r\n"
		    + "    SELECT eb.employeecode, ds.dt AS checkindate\r\n"
		    + "    FROM emp_base eb\r\n"
		    + "    JOIN date_series ds\r\n"
		    + "),\r\n"
		    + "normal_missing_days AS (\r\n"
		    + "    SELECT e.employeecode, e.checkindate\r\n"
		    + "    FROM date_series_with_emp e\r\n"
		    + "    JOIN shiftassigndetails s ON e.employeecode = s.employeecode\r\n"
		    + "        AND DATE(s.effectivefrom) <= e.checkindate\r\n"
		    + "        AND DATE(s.effectiveto) >= e.checkindate\r\n"
		    + "    JOIN shiftmaster sm ON s.shiftcode = sm.shiftcode AND sm.nightshift = 0\r\n"
		    + "    LEFT JOIN company_cte c ON 1=1\r\n"
		    + "    LEFT JOIN attendanceprocess a\r\n"
		    + "        ON a.empcode = e.employeecode\r\n"
		    + "       AND a.checkindate = e.checkindate\r\n"
		    + "       AND FIND_IN_SET(a.attendancemode, c.attendancemode)\r\n"
		    + "       AND a.orgid = ?3\r\n"
		    + "    LEFT JOIN approvalleaves al\r\n"
		    + "        ON al.employeecode = e.employeecode\r\n"
		    + "       AND al.leavedate = e.checkindate\r\n"
		    + "       AND al.orgid = ?3\r\n"
		    + "    LEFT JOIN holidays_cte h ON h.holidaydate = e.checkindate\r\n"
		    + "    LEFT JOIN weekoffs w ON w.weekoffdate = e.checkindate\r\n"
		    + "    WHERE a.empcode IS NULL\r\n"
		    + "      AND al.leavedate IS NULL\r\n"
		    + "      AND h.holidaydate IS NULL\r\n"
		    + "      AND w.weekoffdate IS NULL\r\n"
		    + "),\r\n"
		    + "night_missing_days AS (\r\n"
		    + "    SELECT e.employeecode, e.checkindate\r\n"
		    + "    FROM date_series_with_emp e\r\n"
		    + "    JOIN shiftassigndetails s ON e.employeecode = s.employeecode\r\n"
		    + "        AND DATE(s.effectivefrom) <= e.checkindate\r\n"
		    + "        AND DATE(s.effectiveto) >= e.checkindate\r\n"
		    + "    JOIN shiftmaster sm ON s.shiftcode = sm.shiftcode AND sm.nightshift = 1\r\n"
		    + "    LEFT JOIN company_cte c ON 1=1\r\n"
		    + "    LEFT JOIN attendanceprocess in_entry\r\n"
		    + "        ON in_entry.empcode = e.employeecode\r\n"
		    + "       AND in_entry.checkindate = e.checkindate\r\n"
		    + "       AND LOWER(in_entry.status) = 'in'\r\n"
		    + "       AND FIND_IN_SET(in_entry.attendancemode, c.attendancemode)\r\n"
		    + "       AND in_entry.orgid = ?3\r\n"
		    + "    LEFT JOIN attendanceprocess out_entry\r\n"
		    + "        ON out_entry.empcode = e.employeecode\r\n"
		    + "       AND out_entry.checkindate = DATE_ADD(e.checkindate, INTERVAL 1 DAY)\r\n"
		    + "       AND LOWER(out_entry.status) = 'out'\r\n"
		    + "       AND FIND_IN_SET(out_entry.attendancemode, c.attendancemode)\r\n"
		    + "       AND out_entry.orgid = ?3\r\n"
		    + "    LEFT JOIN approvalleaves al\r\n"
		    + "        ON al.employeecode = e.employeecode\r\n"
		    + "       AND al.leavedate IN (e.checkindate, DATE_ADD(e.checkindate, INTERVAL 1 DAY))\r\n"
		    + "       AND al.orgid = ?3\r\n"
		    + "    LEFT JOIN holidays_cte h ON h.holidaydate = e.checkindate\r\n"
		    + "    LEFT JOIN weekoffs w ON w.weekoffdate = e.checkindate\r\n"
		    + "    WHERE (in_entry.empcode IS NULL OR out_entry.empcode IS NULL)\r\n"
		    + "      AND al.leavedate IS NULL\r\n"
		    + "      AND h.holidaydate IS NULL\r\n"
		    + "      AND w.weekoffdate IS NULL\r\n"
		    + "),\r\n"
		    + "absent_days AS (\r\n"
		    + "    SELECT employeecode, COUNT(*) AS absent\r\n"
		    + "    FROM (\r\n"
		    + "        SELECT employeecode, checkindate FROM normal_missing_days\r\n"
		    + "        UNION ALL\r\n"
		    + "        SELECT employeecode, checkindate FROM night_missing_days\r\n"
		    + "    ) all_absent\r\n"
		    + "    GROUP BY employeecode\r\n"
		    + "),\r\n"
		    + "lop_days_final AS (\r\n"
		    + "    SELECT employeecode, COUNT(*) AS lop\r\n"
		    + "    FROM (\r\n"
		    + "        SELECT employeecode\r\n"
		    + "        FROM approvalleaves\r\n"
		    + "        WHERE leavetype = 'LOSS OF PAY'\r\n"
		    + "          AND leavedate BETWEEN ?1 AND ?2\r\n"
		    + "          AND orgid = ?3\r\n"
		    + "        UNION ALL\r\n"
		    + "        SELECT employeecode FROM normal_missing_days\r\n"
		    + "        UNION ALL\r\n"
		    + "        SELECT employeecode FROM night_missing_days\r\n"
		    + "    ) all_lop\r\n"
		    + "    GROUP BY employeecode\r\n"
		    + "),\r\n"
		    + "normal_attendance AS (\r\n"
		    + "    SELECT\r\n"
		    + "        c.empcode,\r\n"
		    + "        c.checkindate,\r\n"
		    + "        MIN(CASE WHEN LOWER(c.status) = 'in' THEN c.entrytime END) AS intime,\r\n"
		    + "        MAX(CASE WHEN LOWER(c.status) = 'out' THEN c.entrytime END) AS outtime,\r\n"
		    + "        s.intime AS shiftintime,\r\n"
		    + "        s.outtime AS shiftouttime,\r\n"
		    + "        sm.nightshift\r\n"
		    + "    FROM attendanceprocess c\r\n"
		    + "    JOIN company_cte cc ON 1=1\r\n"
		    + "    JOIN shiftassigndetails s\r\n"
		    + "      ON c.empcode = s.employeecode\r\n"
		    + "     AND DATE(s.effectivefrom) <= c.checkindate\r\n"
		    + "     AND DATE(s.effectiveto) >= c.checkindate\r\n"
		    + "    JOIN shiftmaster sm ON s.shiftcode = sm.shiftcode\r\n"
		    + "    WHERE FIND_IN_SET(c.attendancemode, cc.attendancemode)\r\n"
		    + "      AND c.orgid = ?3\r\n"
		    + "      AND sm.nightshift = 0\r\n"
		    + "      AND c.checkindate BETWEEN ?1 AND ?2\r\n"
		    + "    GROUP BY c.empcode, c.checkindate, s.intime, s.outtime, sm.nightshift\r\n"
		    + "),\r\n"
		    + "night_attendance AS (\r\n"
		    + "    SELECT\r\n"
		    + "        in_entry.empcode,\r\n"
		    + "        in_entry.checkindate,\r\n"
		    + "        in_entry.entrytime AS intime,\r\n"
		    + "        out_entry.entrytime AS outtime,\r\n"
		    + "        s.intime AS shiftintime,\r\n"
		    + "        s.outtime AS shiftouttime,\r\n"
		    + "        sm.nightshift\r\n"
		    + "    FROM attendanceprocess in_entry\r\n"
		    + "    JOIN shiftassigndetails s\r\n"
		    + "      ON in_entry.empcode = s.employeecode\r\n"
		    + "     AND DATE(s.effectivefrom) <= in_entry.checkindate\r\n"
		    + "     AND DATE(s.effectiveto) >= in_entry.checkindate\r\n"
		    + "    JOIN shiftmaster sm ON s.shiftcode = sm.shiftcode AND sm.nightshift = 1\r\n"
		    + "    JOIN company_cte cc ON 1=1\r\n"
		    + "    LEFT JOIN attendanceprocess out_entry\r\n"
		    + "      ON out_entry.empcode = in_entry.empcode\r\n"
		    + "     AND LOWER(out_entry.status) = 'OUT'\r\n"
		    + "     AND out_entry.checkindate = DATE_ADD(in_entry.checkindate, INTERVAL 1 DAY)\r\n"
		    + "     AND out_entry.orgid = in_entry.orgid\r\n"
		    + "     AND FIND_IN_SET(out_entry.attendancemode, cc.attendancemode)\r\n"
		    + "    WHERE LOWER(in_entry.status) = 'IN'\r\n"
		    + "      AND in_entry.orgid = ?3\r\n"
		    + "      AND FIND_IN_SET(in_entry.attendancemode, cc.attendancemode)\r\n"
		    + "      AND in_entry.checkindate BETWEEN ?1 AND ?2\r\n"
		    + "),\r\n"
		    + "present_days AS (\r\n"
		    + "    SELECT empcode, SUM(present_day_value) AS presentdays\r\n"
		    + "    FROM (\r\n"
		    + "        SELECT\r\n"
		    + "            empcode,\r\n"
		    + "            checkindate,\r\n"
		    + "            CASE\r\n"
		    + "                WHEN intime IS NOT NULL AND outtime IS NOT NULL THEN\r\n"
		    + "                    CASE\r\n"
		    + "                        WHEN nightshift = 1 THEN\r\n"
		    + "                            CASE\r\n"
		    + "                                WHEN TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                                    STR_TO_DATE(intime, '%H:%i:%s'),\r\n"
		    + "                                    ADDTIME(STR_TO_DATE(outtime, '%H:%i:%s'), '24:00:00')\r\n"
		    + "                                ) >= TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                                    STR_TO_DATE(CONCAT(shiftintime, ':00'), '%H:%i:%s'),\r\n"
		    + "                                    ADDTIME(STR_TO_DATE(CONCAT(shiftouttime, ':00'), '%H:%i:%s'), '24:00:00')\r\n"
		    + "                                ) - 120 THEN 1\r\n"
		    + "                                WHEN TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                                    STR_TO_DATE(intime, '%H:%i:%s'),\r\n"
		    + "                                    ADDTIME(STR_TO_DATE(outtime, '%H:%i:%s'), '24:00:00')\r\n"
		    + "                                ) >= (TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                                    STR_TO_DATE(CONCAT(shiftintime, ':00'), '%H:%i:%s'),\r\n"
		    + "                                    ADDTIME(STR_TO_DATE(CONCAT(shiftouttime, ':00'), '%H:%i:%s'), '24:00:00')\r\n"
		    + "                                ) / 2) - 90 THEN 0.5\r\n"
		    + "                                ELSE 0\r\n"
		    + "                            END\r\n"
		    + "                        ELSE\r\n"
		    + "                            CASE\r\n"
		    + "                                WHEN TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                                    STR_TO_DATE(intime, '%H:%i:%s'),\r\n"
		    + "                                    STR_TO_DATE(outtime, '%H:%i:%s')\r\n"
		    + "                                ) >= TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                                    STR_TO_DATE(CONCAT(shiftintime, ':00'), '%H:%i:%s'),\r\n"
		    + "                                    STR_TO_DATE(CONCAT(shiftouttime, ':00'), '%H:%i:%s')\r\n"
		    + "                                ) - 120 THEN 1\r\n"
		    + "                                WHEN TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                                    STR_TO_DATE(intime, '%H:%i:%s'),\r\n"
		    + "                                    STR_TO_DATE(outtime, '%H:%i:%s')\r\n"
		    + "                                ) >= (TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                                    STR_TO_DATE(CONCAT(shiftintime, ':00'), '%H:%i:%s'),\r\n"
		    + "                                    STR_TO_DATE(CONCAT(shiftouttime, ':00'), '%H:%i:%s')\r\n"
		    + "                                ) / 2) - 90 THEN 0.5\r\n"
		    + "                                ELSE 0\r\n"
		    + "                            END\r\n"
		    + "                    END\r\n"
		    + "                WHEN nightshift = 1 AND intime IS NOT NULL AND outtime IS NULL THEN 0.5\r\n"
		    + "                ELSE 0\r\n"
		    + "            END AS present_day_value\r\n"
		    + "        FROM normal_attendance\r\n"
		    + "        UNION ALL\r\n"
		    + "        SELECT\r\n"
		    + "            empcode,\r\n"
		    + "            checkindate,\r\n"
		    + "            CASE\r\n"
		    + "                WHEN intime IS NOT NULL AND outtime IS NOT NULL THEN\r\n"
		    + "                    CASE\r\n"
		    + "                        WHEN TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                            STR_TO_DATE(intime, '%H:%i:%s'),\r\n"
		    + "                            ADDTIME(STR_TO_DATE(outtime, '%H:%i:%s'), '24:00:00')\r\n"
		    + "                        ) >= TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                            STR_TO_DATE(CONCAT(shiftintime, ':00'), '%H:%i:%s'),\r\n"
		    + "                            ADDTIME(STR_TO_DATE(CONCAT(shiftouttime, ':00'), '%H:%i:%s'), '24:00:00')\r\n"
		    + "                        ) - 120 THEN 1\r\n"
		    + "                        WHEN TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                            STR_TO_DATE(intime, '%H:%i:%s'),\r\n"
		    + "                            ADDTIME(STR_TO_DATE(outtime, '%H:%i:%s'), '24:00:00')\r\n"
		    + "                        ) >= (TIMESTAMPDIFF(MINUTE,\r\n"
		    + "                            STR_TO_DATE(CONCAT(shiftintime, ':00'), '%H:%i:%s'),\r\n"
		    + "                            ADDTIME(STR_TO_DATE(CONCAT(shiftouttime, ':00'), '%H:%i:%s'), '24:00:00')\r\n"
		    + "                        ) / 2) - 90 THEN 0.5\r\n"
		    + "                        ELSE 0\r\n"
		    + "                    END\r\n"
		    + "                WHEN intime IS NOT NULL AND outtime IS NULL THEN 0.5\r\n"
		    + "                ELSE 0\r\n"
		    + "            END AS present_day_value\r\n"
		    + "        FROM night_attendance\r\n"
		    + "    ) all_present\r\n"
		    + "    GROUP BY empcode\r\n"
		    + "),\r\n"
		    + "month_info AS (\r\n"
		    + "    SELECT COUNT(*) AS totaldays FROM date_series\r\n"
		    + "),\r\n"
		    + "leave_days AS (\r\n"
		    + "    SELECT employeecode, COUNT(*) AS leaves\r\n"
		    + "    FROM approvalleaves\r\n"
		    + "    WHERE leavedate BETWEEN ?1 AND ?2\r\n"
		    + "      AND orgid = ?3\r\n"
		    + "    GROUP BY employeecode\r\n"
		    + "),\r\n"
		    + "holiday_count AS (\r\n"
		    + "    SELECT COUNT(*) AS holidays FROM holidays_cte\r\n"
		    + "),\r\n"
		    + "weekoff_count AS (\r\n"
		    + "    SELECT COUNT(*) AS weekoff FROM weekoffs\r\n"
		    + ")\r\n"
		    + "SELECT\r\n"
		    + "    eb.employee AS name,\r\n"
		    + "    eb.employeecode AS code,\r\n"
		    + "    e.branch,\r\n"
		    + "    e.department,\r\n"
		    + "    MONTH(DATE(?1)) AS month,\r\n"
		    + "    YEAR(DATE(?1)) AS year,\r\n"
		    + "    mi.totaldays,\r\n"
		    + "    hc.holidays,\r\n"
		    + "    wc.weekoff AS weekoff,\r\n"
		    + "    COALESCE(ld.leaves, 0) AS leaves,\r\n"
		    + "    COALESCE(abs.absent, 0) AS absent,\r\n"
		    + "    COALESCE(lop.lop, 0) AS lop,\r\n"
		    + "    COALESCE(pd.presentdays, 0) AS presentdays,\r\n"
		    + "    CASE \r\n"
		    + "        WHEN COALESCE(pd.presentdays, 0) > 0 THEN mi.totaldays - COALESCE(lop.lop, 0) \r\n"
		    + "        ELSE 0\r\n"
		    + "    END AS salarydays\r\n"
		    + "FROM emp_base eb\r\n"
		    + "JOIN employee e ON eb.employeecode = e.employeecode\r\n"
		    + "CROSS JOIN month_info mi\r\n"
		    + "CROSS JOIN holiday_count hc\r\n"
		    + "CROSS JOIN weekoff_count wc\r\n"
		    + "LEFT JOIN leave_days ld ON eb.employeecode = ld.employeecode\r\n"
		    + "LEFT JOIN lop_days_final lop ON eb.employeecode = lop.employeecode\r\n"
		    + "LEFT JOIN present_days pd ON eb.employeecode = pd.empcode\r\n"
		    + "LEFT JOIN absent_days abs ON eb.employeecode = abs.employeecode\r\n"
		    + "WHERE (?4 = 'ALL' OR e.department = ?4 )\r\n"
		    + "  AND (?5 = 'ALL' OR e.branch = ?5)\r\n"
		    + "ORDER BY eb.employeecode"
		)
	Set<Object[]> getLeaveDetailsForAttendanceProcess(String fromDate, String toDate, Long orgId, String department,
			String branch);

}
