package com.efit.hrms.repo;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.efit.hrms.entity.AttendanceDailyVO;
import com.efit.hrms.entity.AttendanceProcessVO;

@Repository
public interface AttendanceProcessRepo extends JpaRepository<AttendanceProcessVO, Long>{

//	
//	@Query(nativeQuery = true, value = 
//		    "WITH RECURSIVE date_series AS (\r\n"
//		    + "    SELECT DATE(?1) AS dt\r\n"
//		    + "    UNION ALL\r\n"
//		    + "    SELECT DATE_ADD(dt, INTERVAL 1 DAY)\r\n"
//		    + "    FROM date_series\r\n"
//		    + "    WHERE dt < DATE(?2)\r\n"
//		    + "),\r\n"
//		    + "weekoffs AS (\r\n"
//		    + "    SELECT ds.dt AS weekoffdate\r\n"
//		    + "    FROM date_series ds\r\n"
//		    + "    JOIN companyweekoff cw\r\n"
//		    + "      ON cw.companyid = ?3\r\n"
//		    + "     AND UPPER(DAYNAME(ds.dt)) = UPPER(cw.weekoffdays)\r\n"
//		    + "),\r\n"
//		    + "holidays_cte AS (\r\n"
//		    + "    SELECT holidaydate\r\n"
//		    + "    FROM holidays\r\n"
//		    + "    WHERE orgid = ?3\r\n"
//		    + "      AND holidaydate BETWEEN ?1 AND DATE_SUB(?2, INTERVAL 1 DAY)\r\n"
//		    + "),\r\n"
//		    + "emp_base AS (\r\n"
//		    + "    SELECT DISTINCT lb.employeecode, lb.employee\r\n"
//		    + "    FROM leavebalance lb\r\n"
//		    + "    JOIN employee e ON lb.employeecode = e.employeecode\r\n"
//		    + "    WHERE lb.orgid = ?3\r\n"
//		    + "      AND (?4 = 'ALL' OR e.department = ?4)\r\n"
//		    + "      AND (?5 = 'ALL' OR e.branch = ?5)\r\n"
//		    + "),\r\n"
//		    + "company_cte AS (\r\n"
//		    + "    SELECT * FROM company WHERE companyid = ?3\r\n"
//		    + "),\r\n"
//		    + "date_series_with_emp AS (\r\n"
//		    + "    SELECT eb.employeecode, ds.dt AS checkindate\r\n"
//		    + "    FROM emp_base eb\r\n"
//		    + "    JOIN date_series ds\r\n"
//		    + "),\r\n"
//		    + "missing_days AS (\r\n"
//		    + "    SELECT e.employeecode, e.checkindate\r\n"
//		    + "    FROM date_series_with_emp e\r\n"
//		    + "    LEFT JOIN company_cte c ON 1=1\r\n"
//		    + "    LEFT JOIN attendanceprocess a\r\n"
//		    + "        ON a.empcode = e.employeecode\r\n"
//		    + "       AND a.checkindate = e.checkindate\r\n"
//		    + "       AND FIND_IN_SET(a.attendancemode, c.attendancemode)\r\n"
//		    + "       AND a.orgid = ?3\r\n"
//		    + "    LEFT JOIN approvalleaves al\r\n"
//		    + "        ON al.employeecode = e.employeecode\r\n"
//		    + "       AND al.leavedate = e.checkindate\r\n"
//		    + "       AND al.orgid = ?3\r\n"
//		    + "    LEFT JOIN holidays_cte h ON h.holidaydate = e.checkindate\r\n"
//		    + "    LEFT JOIN weekoffs w ON w.weekoffdate = e.checkindate\r\n"
//		    + "    WHERE a.empcode IS NULL\r\n"
//		    + "      AND al.leavedate IS NULL\r\n"
//		    + "      AND h.holidaydate IS NULL\r\n"
//		    + "      AND w.weekoffdate IS NULL\r\n"
//		    + "),\r\n"
//		    + "lop_days_final AS (\r\n"
//		    + "    SELECT employeecode, COUNT(*) AS lop\r\n"
//		    + "    FROM (\r\n"
//		    + "        SELECT employeecode\r\n"
//		    + "        FROM approvalleaves\r\n"
//		    + "        WHERE leavetype = 'LOSS OF PAY'\r\n"
//		    + "          AND leavedate BETWEEN ?1 AND DATE_SUB(?2, INTERVAL 1 DAY)\r\n"
//		    + "          AND orgid = ?3\r\n"
//		    + "        UNION ALL\r\n"
//		    + "        SELECT employeecode\r\n"
//		    + "        FROM missing_days\r\n"
//		    + "    ) all_lop\r\n"
//		    + "    GROUP BY employeecode\r\n"
//		    + "),\r\n"
//		    + "absent_days AS (\r\n"
//		    + "    SELECT employeecode, COUNT(*) AS absent\r\n"
//		    + "    FROM missing_days\r\n"
//		    + "    GROUP BY employeecode\r\n"
//		    + "),\r\n"
//		    + "present_days AS (\r\n"
//		    + "    SELECT empcode, SUM(present_day_value) AS presentdays\r\n"
//		    + "    FROM (\r\n"
//		    + "        SELECT\r\n"
//		    + "            c.empcode,\r\n"
//		    + "            c.checkindate,\r\n"
//		    + "            CASE\r\n"
//		    + "                WHEN MIN(CASE WHEN LOWER(c.status) = 'in' THEN c.entrytime END) IS NOT NULL\r\n"
//		    + "                  AND MAX(CASE WHEN LOWER(c.status) = 'out' THEN c.entrytime END) IS NOT NULL\r\n"
//		    + "                  AND TIMESTAMPDIFF(MINUTE,\r\n"
//		    + "                        STR_TO_DATE(MIN(CASE WHEN LOWER(c.status) = 'in' THEN c.entrytime END), '%H:%i:%s'),\r\n"
//		    + "                        STR_TO_DATE(MAX(CASE WHEN LOWER(c.status) = 'out' THEN c.entrytime END), '%H:%i:%s')\r\n"
//		    + "                    ) >= TIMESTAMPDIFF(MINUTE,\r\n"
//		    + "                        STR_TO_DATE(CONCAT(s.intime, ':00'), '%H:%i:%s'),\r\n"
//		    + "                        STR_TO_DATE(CONCAT(s.outtime, ':00'), '%H:%i:%s')\r\n"
//		    + "                    ) - 120 THEN 1\r\n"
//		    + "                WHEN MIN(CASE WHEN LOWER(c.status) = 'in' THEN c.entrytime END) IS NOT NULL\r\n"
//		    + "                  AND MAX(CASE WHEN LOWER(c.status) = 'out' THEN c.entrytime END) IS NOT NULL\r\n"
//		    + "                  AND TIMESTAMPDIFF(MINUTE,\r\n"
//		    + "                        STR_TO_DATE(MIN(CASE WHEN LOWER(c.status) = 'in' THEN c.entrytime END), '%H:%i:%s'),\r\n"
//		    + "                        STR_TO_DATE(MAX(CASE WHEN LOWER(c.status) = 'out' THEN c.entrytime END), '%H:%i:%s')\r\n"
//		    + "                    ) >= (TIMESTAMPDIFF(MINUTE,\r\n"
//		    + "                        STR_TO_DATE(CONCAT(s.intime, ':00'), '%H:%i:%s'),\r\n"
//		    + "                        STR_TO_DATE(CONCAT(s.outtime, ':00'), '%H:%i:%s')\r\n"
//		    + "                    ) / 2) - 90 THEN 0.5\r\n"
//		    + "                ELSE 0\r\n"
//		    + "            END AS present_day_value\r\n"
//		    + "        FROM attendanceprocess c\r\n"
//		    + "        JOIN company_cte cc ON 1=1\r\n"
//		    + "        JOIN shiftassigndetails s\r\n"
//		    + "          ON c.empcode = s.employeecode\r\n"
//		    + "         AND DATE(s.effectivefrom) <= c.checkindate\r\n"
//		    + "         AND DATE(s.effectiveto) >= c.checkindate\r\n"
//		    + "        WHERE FIND_IN_SET(c.attendancemode, cc.attendancemode)\r\n"
//		    + "          AND c.orgid = ?3\r\n"
//		    + "          AND c.checkindate BETWEEN ?1 AND DATE_SUB(?2, INTERVAL 1 DAY)\r\n"
//		    + "        GROUP BY c.empcode, c.checkindate, s.intime, s.outtime\r\n"
//		    + "    ) x\r\n"
//		    + "    GROUP BY empcode\r\n"
//		    + "),\r\n"
//		    + "month_info AS (\r\n"
//		    + "    SELECT COUNT(*) AS totaldays FROM date_series\r\n"
//		    + "),\r\n"
//		    + "leave_days AS (\r\n"
//		    + "    SELECT employeecode, COUNT(*) AS leaves\r\n"
//		    + "    FROM approvalleaves\r\n"
//		    + "    WHERE leavedate BETWEEN ?1 AND DATE_SUB(?2, INTERVAL 1 DAY)\r\n"
//		    + "      AND orgid = ?3\r\n"
//		    + "    GROUP BY employeecode\r\n"
//		    + "),\r\n"
//		    + "holiday_count AS (\r\n"
//		    + "    SELECT COUNT(*) AS holidays FROM holidays_cte\r\n"
//		    + "),\r\n"
//		    + "weekoff_count AS (\r\n"
//		    + "    SELECT COUNT(*) AS weekoff FROM weekoffs\r\n"
//		    + ")\r\n"
//		    + "\r\n"
//		    + "SELECT\r\n"
//		    + "    eb.employee AS name,\r\n"
//		    + "    eb.employeecode AS code,\r\n"
//		    + "    e.branch,\r\n"
//		    + "    e.department,\r\n"
//		    + "    MONTH(DATE(?1)) AS month,\r\n"
//		    + "    YEAR(DATE(?1)) AS year,\r\n"
//		    + "    mi.totaldays,\r\n"
//		    + "    hc.holidays,\r\n"
//		    + "    wc.weekoff AS weekoff,\r\n"
//		    + "    COALESCE(ld.leaves, 0) AS leaves,\r\n"
//		    + "    COALESCE(abs.absent, 0) AS absent,\r\n"
//		    + "    COALESCE(lop.lop, 0) AS lop,\r\n"
//		    + "    COALESCE(pd.presentdays, 0) AS presentdays,\r\n"
//		    + "    CASE \r\n"
//		    + "        WHEN COALESCE(pd.presentdays, 0) > 0 THEN mi.totaldays - COALESCE(lop.lop, 0) \r\n"
//		    + "        ELSE 0\r\n"
//		    + "    END AS salarydays\r\n"
//		    + "FROM emp_base eb\r\n"
//		    + "JOIN employee e ON eb.employeecode = e.employeecode\r\n"
//		    + "CROSS JOIN month_info mi\r\n"
//		    + "CROSS JOIN holiday_count hc\r\n"
//		    + "CROSS JOIN weekoff_count wc\r\n"
//		    + "LEFT JOIN leave_days ld ON eb.employeecode = ld.employeecode\r\n"
//		    + "LEFT JOIN lop_days_final lop ON eb.employeecode = lop.employeecode\r\n"
//		    + "LEFT JOIN present_days pd ON eb.employeecode = pd.empcode\r\n"
//		    + "LEFT JOIN absent_days abs ON eb.employeecode = abs.employeecode\r\n"
//		    + "ORDER BY eb.employeecode;\r\n"
//		    + ""
//		)
//	Set<Object[]> getLeaveDetailsForAttendanceProcess(String fromDate, String toDate, Long orgId, String department,
//			String branch);
//
//	
	
	
	
	
	@Query(nativeQuery = true, value = 
		    "WITH RECURSIVE date_series AS (\r\n"
		    + "    SELECT DATE(?1) AS dt\r\n"
		    + "    UNION ALL\r\n"
		    + "    SELECT DATE_ADD(dt, INTERVAL 1 DAY)\r\n"
		    + "    FROM date_series\r\n"
		    + "    WHERE dt < DATE(?2)\r\n"
		    + "),\r\n"
		    + "weekoffs AS (\r\n"
		    + "    SELECT ds.dt AS weekoffdate\r\n"
		    + "    FROM date_series ds\r\n"
		    + "    JOIN companyweekoff cw\r\n"
		    + "      ON cw.companyid = ?3\r\n"
		    + "     AND UPPER(DAYNAME(ds.dt)) = UPPER(cw.weekoffdays)\r\n"
		    + "),\r\n"
		    + "holidays_cte AS (\r\n"
		    + "    SELECT holidaydate\r\n"
		    + "    FROM holidays\r\n"
		    + "    WHERE orgid = ?3\r\n"
		    + "      AND holidaydate BETWEEN ?1 AND ?2\r\n"
		    + "),\r\n"
		    + "emp_base AS (\r\n"
		    + "    SELECT e.employeecode, e.employee, e.department, e.branch,e.branchcode \r\n"
		    + "    FROM employee e\r\n"
		    + "    WHERE e.active = 1\r\n"
		    + "      AND e.orgid = ?3\r\n"
		    + "      AND (?4 = 'ALL' OR e.department = ?4)\r\n"
		    + "      AND (?5 = 'ALL' OR e.branch = ?5)"
		    + "     AND ( \r\n"
		    + "      ?6 = 'ALL' \r\n"
		    + "		 OR (?6 = 'EMPLOYEE' AND e.type = 'EMPLOYEE') \r\n"
		    + "	    OR (?6 = 'CONTRACTOR' AND e.type = 'CONTRACTOR' AND e.contractor = ?7) \r\n"
		    + "		 )\r\n"
		    + "),\r\n"
		    + "date_series_with_emp AS (\r\n"
		    + "    SELECT eb.employeecode, ds.dt AS checkindate\r\n"
		    + "    FROM emp_base eb\r\n"
		    + "    JOIN date_series ds\r\n"
		    + "),\r\n"
		    + "shift_hours AS (\r\n"
		    + "  SELECT \r\n"
		    + "    sm.shiftcode,\r\n"
		    + "    sm.intime,\r\n"
		    + "    sm.outtime,\r\n"
		    + "    sm.nightshift,\r\n"
		    + "    CASE \r\n"
		    + "      WHEN STR_TO_DATE(sm.outtime, '%H:%i') > STR_TO_DATE(sm.intime, '%H:%i')\r\n"
		    + "        THEN TIMESTAMPDIFF(MINUTE, STR_TO_DATE(sm.intime, '%H:%i'), STR_TO_DATE(sm.outtime, '%H:%i')) / 60.0\r\n"
		    + "      ELSE (TIMESTAMPDIFF(MINUTE, STR_TO_DATE(sm.intime, '%H:%i'), ADDTIME(STR_TO_DATE(sm.outtime, '%H:%i'), '24:00:00')) / 60.0)\r\n"
		    + "    END AS shifthours\r\n"
		    + "  FROM shiftmaster sm\r\n"
		    + "),\r\n"
		    + "att_data AS (\r\n"
		    + "    SELECT\r\n"
		    + "        a.empcode,\r\n"
		    + "        a.checkindate,\r\n"
		    + "        SUM(a.effectivehours) AS total_effectivehours,\r\n"
		    + "        CASE\r\n"
		    + "            WHEN SUM(a.effectivehours) >= sh.shifthours THEN 1\r\n"
		    + "            WHEN SUM(a.effectivehours) >= sh.shifthours / 2 THEN 0.5\r\n"
		    + "            ELSE 0\r\n"
		    + "        END AS present_value\r\n"
		    + "    FROM attendancedaily a\r\n"
		    + "    JOIN shiftassigndetails sd\r\n"
		    + "      ON a.empcode = sd.employeecode\r\n"
		    + "     AND DATE(sd.effectivefrom) <= a.checkindate\r\n"
		    + "     AND DATE(sd.effectiveto) >= a.checkindate\r\n"
		    + "    JOIN shift_hours sh ON sh.shiftcode = sd.shiftcode\r\n"
		    + "    WHERE a.checkindate BETWEEN ?1 AND ?2\r\n"
		    + "      AND a.orgid = ?3\r\n"
		    + "    GROUP BY a.empcode, a.checkindate, sh.shifthours\r\n"
		    + "),\r\n"
		    + "present_days AS (\r\n"
		    + "    SELECT empcode, SUM(present_value) AS presentdays\r\n"
		    + "    FROM att_data\r\n"
		    + "    GROUP BY empcode\r\n"
		    + "),\r\n"
		    + "leave_days AS (\r\n"
		    + "    SELECT employeecode, COUNT(*) AS leaves\r\n"
		    + "    FROM approvalleaves\r\n"
		    + "    WHERE orgid = ?3\r\n"
		    + "      AND leavedate BETWEEN ?1 AND ?2\r\n"
		    + "    GROUP BY employeecode\r\n"
		    + "),\r\n"
		    + "normal_missing_days AS (\r\n"
		    + "    SELECT e.employeecode, e.checkindate\r\n"
		    + "    FROM date_series_with_emp e\r\n"
		    + "    LEFT JOIN att_data a ON e.employeecode = a.empcode AND e.checkindate = a.checkindate\r\n"
		    + "    LEFT JOIN approvalleaves al ON al.employeecode = e.employeecode AND al.leavedate = e.checkindate AND al.orgid = ?3\r\n"
		    + "    LEFT JOIN holidays_cte h ON h.holidaydate = e.checkindate\r\n"
		    + "    LEFT JOIN weekoffs w ON w.weekoffdate = e.checkindate\r\n"
		    + "    WHERE a.empcode IS NULL\r\n"
		    + "      AND al.leavedate IS NULL\r\n"
		    + "      AND h.holidaydate IS NULL\r\n"
		    + "      AND w.weekoffdate IS NULL\r\n"
		    + "),\r\n"
		    + "night_missing_days AS (\r\n"
		    + "    SELECT nm.employeecode, nm.checkindate\r\n"
		    + "    FROM normal_missing_days nm\r\n"
		    + "    JOIN shiftassigndetails s\r\n"
		    + "      ON nm.employeecode = s.employeecode\r\n"
		    + "     AND DATE(s.effectivefrom) <= nm.checkindate\r\n"
		    + "     AND DATE(s.effectiveto) >= nm.checkindate\r\n"
		    + "    JOIN shiftmaster sm ON sm.shiftcode = s.shiftcode AND sm.nightshift = 1\r\n"
		    + "),\r\n"
		    + "absent_days AS (\r\n"
		    + "  SELECT empcode AS employeecode, SUM(abs_value) AS absent\r\n"
		    + "  FROM (\r\n"
		    + "      SELECT empcode, 1 AS abs_value\r\n"
		    + "      FROM att_data\r\n"
		    + "      WHERE present_value = 0\r\n"
		    + "\r\n"
		    + "      UNION ALL\r\n"
		    + "\r\n"
		    + "      SELECT empcode, 0.5 AS abs_value\r\n"
		    + "      FROM att_data\r\n"
		    + "      WHERE present_value = 0.5\r\n"
		    + "\r\n"
		    + "      UNION ALL\r\n"
		    + "\r\n"
		    + "      SELECT employeecode, 1 FROM normal_missing_days\r\n"
		    + "      UNION ALL\r\n"
		    + "      SELECT employeecode, 1 FROM night_missing_days\r\n"
		    + "  ) all_abs\r\n"
		    + "  GROUP BY empcode\r\n"
		    + "),\r\n"
		    + "lop_days AS (\r\n"
		    + "  SELECT employeecode AS employeecode, SUM(lop_value) AS lop\r\n"
		    + "  FROM (\r\n"
		    + "      SELECT employeecode, 1 AS lop_value\r\n"
		    + "      FROM approvalleaves\r\n"
		    + "      WHERE leavetype = 'LOSS OF PAY'\r\n"
		    + "        AND leavedate BETWEEN ?1 AND ?2\r\n"
		    + "        AND orgid = ?3\r\n"
		    + "\r\n"
		    + "      UNION ALL\r\n"
		    + "\r\n"
		    + "      SELECT empcode, 1 FROM att_data WHERE present_value = 0\r\n"
		    + "      UNION ALL\r\n"
		    + "      SELECT empcode, 0.5 FROM att_data WHERE present_value = 0.5\r\n"
		    + "\r\n"
		    + "      UNION ALL\r\n"
		    + "      SELECT employeecode, 1 FROM normal_missing_days\r\n"
		    + "      UNION ALL\r\n"
		    + "      SELECT employeecode, 1 FROM night_missing_days\r\n"
		    + "  ) all_lop\r\n"
		    + "  GROUP BY employeecode\r\n"
		    + "),\r\n"
		    + "month_info AS (\r\n"
		    + "    SELECT COUNT(*) AS totaldays FROM date_series\r\n"
		    + "),\r\n"
		    + "holiday_count AS (\r\n"
		    + "    SELECT COUNT(*) AS holidays FROM holidays_cte\r\n"
		    + "),\r\n"
		    + "weekoff_count AS (\r\n"
		    + "    SELECT COUNT(*) AS weekoff FROM weekoffs\r\n"
		    + ")\r\n"
		    + "SELECT\r\n"
		    + "    eb.employee AS name,\r\n"
		    + "    eb.employeecode AS code,"
		    + "    eb.branch As branch,"
		    + "    eb.branchcode As branchcode,\r\n"
		    + "    eb.department As department,\r\n"
		    + "    MONTH(DATE(?1)) AS month,\r\n"
		    + "    YEAR(DATE(?1)) AS year,\r\n"
		    + "    mi.totaldays As totaldays,\r\n"
		    + "    hc.holidays As holidays, \r\n"
		    + "    wc.weekoff As weekoff,\r\n"
		    + "    COALESCE(ld.leaves, 0) AS leaves,\r\n"
		    + "    COALESCE(lop.lop, 0) AS lop,\r\n"
		    + "    COALESCE(abs.absent, 0) AS absent,\r\n"
		    + "    COALESCE(pd.presentdays, 0) AS presentdays,\r\n"
		    + "    CASE \r\n"
		    + "        WHEN COALESCE(pd.presentdays, 0) > 0 THEN mi.totaldays - COALESCE(lop.lop, 0)\r\n"
		    + "        ELSE 0\r\n"
		    + "    END AS salarydays\r\n"
		    + "FROM emp_base eb\r\n"
		    + "CROSS JOIN month_info mi\r\n"
		    + "CROSS JOIN holiday_count hc\r\n"
		    + "CROSS JOIN weekoff_count wc\r\n"
		    + "LEFT JOIN leave_days ld ON eb.employeecode = ld.employeecode\r\n"
		    + "LEFT JOIN lop_days lop ON eb.employeecode = lop.employeecode\r\n"
		    + "LEFT JOIN absent_days abs ON eb.employeecode = abs.employeecode\r\n"
		    + "LEFT JOIN present_days pd ON eb.employeecode = pd.empcode \r\n"
		    + "WHERE NOT EXISTS (\r\n"
		    + "    SELECT 1\r\n"
		    + "    FROM attendancesummary ats\r\n"
		    + "    WHERE ats.month = MONTH(DATE(?1))\r\n"
		    + "      AND ats.year = YEAR(DATE(?1))\r\n"
		    + "      AND ats.orgid = ?3\r\n"
		    + "      AND ats.empcode = eb.employeecode\r\n"
		    + "      AND ats.branchcode = eb.branchcode\r\n"
		    + ")\r\n"
		    + "ORDER BY eb.employeecode \r\n"
		    + ""
		)
	Set<Object[]> getLeaveDetailsForAttendanceProcess(String fromDate, String toDate, Long orgId, String department,
			String branch, String type,String contractor);

	
	
	
	@Query(nativeQuery = true, value = 
		    "WITH RECURSIVE date_series AS (\r\n"
		    + "    SELECT DATE(CONCAT(?2, '-', LPAD(?1, 2, '0'), '-01')) AS dt\r\n"
		    + "    UNION ALL\r\n"
		    + "    SELECT DATE_ADD(dt, INTERVAL 1 DAY)\r\n"
		    + "    FROM date_series\r\n"
		    + "    WHERE MONTH(dt) = ?1 AND YEAR(dt) = ?2\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "company_attendance_mode AS (\r\n"
		    + "    SELECT attendancemode \r\n"
		    + "    FROM company \r\n"
		    + "    WHERE companyid = ?3\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "paired_attendance AS (\r\n"
		    + "    SELECT \r\n"
		    + "        ap.empcode,\r\n"
		    + "        ap.empname,\r\n"
		    + "        ap.branch,\r\n"
		    + "        e.department,\r\n"
		    + "        s.shifttype,\r\n"
		    + "        ap.checkindate,\r\n"
		    + "        ap.entrytime,\r\n"
		    + "        ap.status,\r\n"
		    + "        s.intime,\r\n"
		    + "        s.outtime,\r\n"
		    + "        CASE WHEN LOWER(s.shifttype) = 'night' THEN 1 ELSE 0 END AS nightShift,\r\n"
		    + "        sa.orgid,\r\n"
		    + "        ROW_NUMBER() OVER (\r\n"
		    + "            PARTITION BY ap.empcode, ap.checkindate, ap.status \r\n"
		    + "            ORDER BY ap.entrytime\r\n"
		    + "        ) AS rn\r\n"
		    + "    FROM attendanceprocess ap\r\n"
		    + "    JOIN company_attendance_mode cam \r\n"
		    + "        ON FIND_IN_SET(ap.attendancemode, cam.attendancemode) > 0\r\n"
		    + "    JOIN employee e \r\n"
		    + "        ON e.employeecode = ap.empcode AND e.orgid = ap.orgid\r\n"
		    + "    JOIN shiftassigndetails s \r\n"
		    + "        ON s.employeecode = ap.empcode \r\n"
		    + "        AND ap.checkindate BETWEEN s.effectivefrom AND s.effectiveto\r\n"
		    + "    JOIN shiftassign sa \r\n"
		    + "        ON sa.shiftassignid = s.shiftassignid AND sa.orgid = ap.orgid\r\n"
		    + "    WHERE ap.orgid = ?3\r\n"
		    + "      AND (?4 = 'ALL' OR e.branch = ?4)\r\n"
		    + "  AND (?5 = 'ALL' OR e.department = ?5)\r\n"
		    + "  AND (\r\n"
		    + "      ?6 = 'ALL'\r\n"
		    + "      OR (?6 = 'EMPLOYEE' AND e.type = 'EMPLOYEE')\r\n"
		    + "      OR (?6 = 'CONTRACTOR' AND e.type = 'CONTRACTOR' AND e.contractor = ?7)\r\n"
		    + "  )\r\n"
		    + ""
		    + "),\r\n"
		    + "\r\n"
		    + "matched_attendance AS (\r\n"
		    + "    SELECT\r\n"
		    + "        in_rec.empcode,\r\n"
		    + "        in_rec.empname,\r\n"
		    + "        in_rec.branch,\r\n"
		    + "        in_rec.department,\r\n"
		    + "        in_rec.shifttype AS shift_type,\r\n"
		    + "        in_rec.checkindate AS in_date,\r\n"
		    + "        in_rec.entrytime AS in_time,\r\n"
		    + "        out_rec.checkindate AS out_date,\r\n"
		    + "        out_rec.entrytime AS out_time,\r\n"
		    + "        in_rec.nightShift\r\n"
		    + "    FROM paired_attendance in_rec\r\n"
		    + "    JOIN paired_attendance out_rec \r\n"
		    + "        ON in_rec.empcode = out_rec.empcode\r\n"
		    + "        AND in_rec.rn = out_rec.rn\r\n"
		    + "        AND in_rec.status = 'IN'\r\n"
		    + "        AND out_rec.status = 'OUT'\r\n"
		    + "        AND (\r\n"
		    + "            (in_rec.nightShift = 0 AND in_rec.checkindate = out_rec.checkindate)\r\n"
		    + "            OR (in_rec.nightShift = 1 AND DATE_ADD(in_rec.checkindate, INTERVAL 1 DAY) = out_rec.checkindate)\r\n"
		    + "        )\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "worked_hours AS (\r\n"
		    + "    SELECT\r\n"
		    + "        empcode,\r\n"
		    + "        empname,\r\n"
		    + "        branch,\r\n"
		    + "        department,\r\n"
		    + "        shift_type,\r\n"
		    + "        in_date AS actual_date,\r\n"
		    + "           GREATEST(FLOOR(TIMESTAMPDIFF(SECOND,\r\n"
		    + "            STR_TO_DATE(CONCAT(in_date, ' ', in_time), '%Y-%m-%d %H:%i:%s'),\r\n"
		    + "            STR_TO_DATE(CONCAT(out_date, ' ', out_time), '%Y-%m-%d %H:%i:%s')\r\n"
		    + "        ) / 3600), 0) AS work_hours\r\n"
		    + "    FROM matched_attendance\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "leave_data AS (\r\n"
		    + "    SELECT \r\n"
		    + "        employeecode AS empcode,\r\n"
		    + "        DATE(leavedate) AS leavedate\r\n"
		    + "    FROM approvalleaves\r\n"
		    + "    WHERE orgid = ?3\r\n"
		    + "      AND approvestatus = 'APPROVED'\r\n"
		    + "      AND leavedate BETWEEN DATE(CONCAT(?2, '-', LPAD(?1, 2, '0'), '-01'))\r\n"
		    + "                      AND LAST_DAY(DATE(CONCAT(?2, '-', LPAD(?1, 2, '0'), '-01')))\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "all_emp_dates AS (\r\n"
		    + "    SELECT \r\n"
		    + "        DISTINCT e.employeecode AS empcode,\r\n"
		    + "        e.employee AS empname,\r\n"
		    + "        e.branch,\r\n"
		    + "        e.department,\r\n"
		    + "        s.shifttype AS shift_type,\r\n"
		    + "        ds.dt AS actual_date\r\n"
		    + "    FROM date_series ds\r\n"
		    + "    JOIN employee e ON e.orgid = ?3\r\n"
		    + "    JOIN shiftassigndetails s \r\n"
		    + "        ON s.employeecode = e.employeecode \r\n"
		    + "        AND ds.dt BETWEEN s.effectivefrom AND s.effectiveto\r\n"
		    + "    JOIN shiftassign sa \r\n"
		    + "        ON sa.shiftassignid = s.shiftassignid \r\n"
		    + "        AND sa.orgid = ?3\r\n"
		    + "    WHERE (?4 = 'ALL' OR e.branch = ?4)\r\n"
		    + "  AND (?5 = 'ALL' OR e.department = ?5)\r\n"
		    + "  AND (\r\n"
		    + "      ?6 = 'ALL'\r\n"
		    + "      OR (?6 = 'EMPLOYEE' AND e.type = 'EMPLOYEE')\r\n"
		    + "      OR (?6 = 'CONTRACTOR' AND e.type = 'CONTRACTOR' AND e.contractor = ?7)\r\n"
		    + "  )\r\n"
		    + "\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "pivot_data AS (\r\n"
		    + "    SELECT \r\n"
		    + "        a.empcode,\r\n"
		    + "        a.empname,\r\n"
		    + "        a.branch,\r\n"
		    + "        a.department,\r\n"
		    + "        a.shift_type,\r\n"
		    + "        a.actual_date,\r\n"
		    + "        CASE \r\n"
		    + "            WHEN l.empcode IS NOT NULL THEN 'L'\r\n"
		    + "            WHEN w.work_hours IS NOT NULL THEN CAST(w.work_hours AS CHAR)\r\n"
		    + "            ELSE '0'\r\n"
		    + "        END AS worked_value\r\n"
		    + "    FROM all_emp_dates a\r\n"
		    + "    LEFT JOIN worked_hours w \r\n"
		    + "        ON a.empcode = w.empcode AND a.actual_date = w.actual_date\r\n"
		    + "    LEFT JOIN leave_data l \r\n"
		    + "        ON a.empcode = l.empcode AND a.actual_date = l.leavedate\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "final_output AS (\r\n"
		    + "    SELECT \r\n"
		    + "        empcode AS code,\r\n"
		    + "        empname AS name,\r\n"
		    + "        branch,\r\n"
		    + "        department,\r\n"
		    + "        shift_type AS shifttype,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 1 THEN worked_value END) AS day_1,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 2 THEN worked_value END) AS day_2,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 3 THEN worked_value END) AS day_3,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 4 THEN worked_value END) AS day_4,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 5 THEN worked_value END) AS day_5,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 6 THEN worked_value END) AS day_6,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 7 THEN worked_value END) AS day_7,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 8 THEN worked_value END) AS day_8,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 9 THEN worked_value END) AS day_9,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 10 THEN worked_value END) AS day_10,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 11 THEN worked_value END) AS day_11,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 12 THEN worked_value END) AS day_12,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 13 THEN worked_value END) AS day_13,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 14 THEN worked_value END) AS day_14,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 15 THEN worked_value END) AS day_15,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 16 THEN worked_value END) AS day_16,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 17 THEN worked_value END) AS day_17,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 18 THEN worked_value END) AS day_18,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 19 THEN worked_value END) AS day_19,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 20 THEN worked_value END) AS day_20,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 21 THEN worked_value END) AS day_21,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 22 THEN worked_value END) AS day_22,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 23 THEN worked_value END) AS day_23,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 24 THEN worked_value END) AS day_24,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 25 THEN worked_value END) AS day_25,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 26 THEN worked_value END) AS day_26,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 27 THEN worked_value END) AS day_27,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 28 THEN worked_value END) AS day_28,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 29 THEN worked_value END) AS day_29,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 30 THEN worked_value END) AS day_30,\r\n"
		    + "        MAX(CASE WHEN DAY(actual_date) = 31 THEN worked_value END) AS day_31\r\n"
		    + "    FROM pivot_data\r\n"
		    + "    GROUP BY empcode, empname, branch, department, shift_type\r\n"
		    + "    ORDER BY empname\r\n"
		    + ")\r\n"
		    + "\r\n"
		    + "SELECT * FROM final_output \r\n"
		    + ""
		)
	List<Map<String, Object>> findMonthlyProcess(
		    int month,
		    int year,
		    Long orgId,
		    String branch,
		    String department,
		    String type,
		    String contractor);




	@Query("SELECT a FROM AttendanceProcessVO a WHERE a.empCode = :empCode AND a.orgId = :orgId AND a.branch = :branch AND a.checkInDate BETWEEN :fromDate AND :toDate ORDER BY a.checkInDate, a.entryTime")
	List<AttendanceProcessVO> findByEmpCodeAndDateRange(
	    @Param("empCode") String empCode,
	    @Param("fromDate") LocalDate fromDate,
	    @Param("toDate") LocalDate toDate,
	    @Param("orgId") Long orgId,
	    @Param("branch") String branch
	);




	Optional<AttendanceProcessVO> findTopByEmpCodeAndStatusAndOrgIdAndBranchAndCheckInDateLessThanEqualOrderByCheckInDateDescEntryTimeDesc(
			String empcode, String string, long orgId, String branch, LocalDate today);


	


}
