package com.efit.hrms.repo;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.efit.hrms.entity.AttendanceDailyVO;
import com.efit.hrms.entity.OtMasterVO;

@Repository
public interface OtMasterRepo extends JpaRepository<OtMasterVO, Long>{

	@Query( value = "SELECT * FROM otmaster WHERE orgid=?1",nativeQuery = true)
	List<OtMasterVO> getAllOtMasterByOrgId(Long orgId);

	@Query( value = "SELECT * FROM otmaster WHERE otmasterid=?1",nativeQuery = true)
	OtMasterVO getOtMasterById(Long id);

	@Query(value = "SELECT e.employeecode, e.employee " +
            "FROM employee e " +
            "WHERE e.orgid = ?1 " +
            "  AND (?2 = 'ALL' OR e.branch = ?2) " +
            "  AND (?3 = 'ALL' OR e.department = ?3) " +
            "  AND ( ?4 = 'ALL' " +
            "        OR (?4 = 'EMPLOYEE' AND e.type = 'EMPLOYEE') " +
            "        OR (?4 = 'CONTRACTOR' AND e.type = 'CONTRACTOR' AND (?5 IS NULL OR e.contractor = ?5)) " +
            "      )", nativeQuery = true)
List<Object[]> getEmployeeNameForApprovalOtProcess(Long orgId, String branch, String department, String type, String contractor);


    @Query(
        value =
            "WITH\r\n"
            + "\r\n"
            + "/* ============================================================\r\n"
            + "   1. REPORT PERIOD\r\n"
            + "   ============================================================ */\r\n"
            + "\r\n"
            + "report_period AS\r\n"
            + "(\r\n"
            + "    SELECT\r\n"
            + "\r\n"
            + "        CAST(?1 AS DATE) AS from_date,\r\n"
            + "\r\n"
            + "        CAST(?2 AS DATE) AS to_date\r\n"
            + "),\r\n"
            + "\r\n"
            + "\r\n"
            + "/* ============================================================\r\n"
            + "   2. COMPANY SETTINGS\r\n"
            + "   ============================================================ */\r\n"
            + "\r\n"
            + "company_settings AS\r\n"
            + "(\r\n"
            + "    SELECT\r\n"
            + "\r\n"
            + "        c.companyid,\r\n"
            + "\r\n"
            + "        c.shifthours,\r\n"
            + "\r\n"
            + "        c.oteligiblehours\r\n"
            + "\r\n"
            + "    FROM company c\r\n"
            + "\r\n"
            + "    WHERE c.companyid = ?3 \r\n"
            + "),\r\n"
            + "\r\n"
            + "\r\n"
            + "/* ============================================================\r\n"
            + "   3. ATTENDANCE RAW\r\n"
            + "   ============================================================ */\r\n"
            + "\r\n"
            + "attendance_raw AS\r\n"
            + "(\r\n"
            + "    SELECT\r\n"
            + "\r\n"
            + "        ad.attendancedailyid,\r\n"
            + "\r\n"
            + "        ad.checkindate,\r\n"
            + "\r\n"
            + "        ad.checkoutdate,\r\n"
            + "\r\n"
            + "        ad.empcode,\r\n"
            + "\r\n"
            + "        ad.empname,\r\n"
            + "\r\n"
            + "        ad.intime,\r\n"
            + "\r\n"
            + "        ad.outtime,\r\n"
            + "\r\n"
            + "        TIMESTAMP(\r\n"
            + "            ad.checkindate,\r\n"
            + "            ad.intime\r\n"
            + "        ) AS in_datetime,\r\n"
            + "\r\n"
            + "        TIMESTAMP(\r\n"
            + "            ad.checkoutdate,\r\n"
            + "            ad.outtime\r\n"
            + "        ) AS out_datetime\r\n"
            + "\r\n"
            + "    FROM attendancedaily ad\r\n"
            + "\r\n"
            + "    CROSS JOIN report_period rp\r\n"
            + "\r\n"
            + "    WHERE\r\n"
            + "\r\n"
            + "        ad.checkindate >= rp.from_date\r\n"
            + "\r\n"
            + "        AND ad.checkindate <\r\n"
            + "            DATE_ADD(\r\n"
            + "                rp.to_date,\r\n"
            + "                INTERVAL 1 DAY\r\n"
            + "            )\r\n"
            + "\r\n"
            + "        AND ad.empcode IS NOT NULL\r\n"
            + "\r\n"
            + "        AND TRIM(ad.empcode) <> ''\r\n"
            + "\r\n"
            + "        AND ad.intime IS NOT NULL\r\n"
            + "\r\n"
            + "        AND ad.outtime IS NOT NULL\r\n"
            + "\r\n"
            + "        AND ad.checkindate IS NOT NULL\r\n"
            + "\r\n"
            + "        AND ad.checkoutdate IS NOT NULL\r\n"
            + "),\r\n"
            + "\r\n"
            + "\r\n"
            + "/* ============================================================\r\n"
            + "   4. DAILY ATTENDANCE\r\n"
            + "   ============================================================ */\r\n"
            + "\r\n"
            + "daily_attendance AS\r\n"
            + "(\r\n"
            + "    SELECT\r\n"
            + "\r\n"
            + "        ar.empcode AS employeecode,\r\n"
            + "\r\n"
            + "        MAX(\r\n"
            + "            ar.empname\r\n"
            + "        ) AS employeename,\r\n"
            + "\r\n"
            + "        ar.checkindate AS attendancedate,\r\n"
            + "\r\n"
            + "        MIN(\r\n"
            + "            ar.in_datetime\r\n"
            + "        ) AS first_in,\r\n"
            + "\r\n"
            + "        MAX(\r\n"
            + "            ar.out_datetime\r\n"
            + "        ) AS last_out,\r\n"
            + "\r\n"
            + "        TIMESTAMPDIFF(\r\n"
            + "            MINUTE,\r\n"
            + "            MIN(ar.in_datetime),\r\n"
            + "            MAX(ar.out_datetime)\r\n"
            + "        ) AS actual_work_minutes\r\n"
            + "\r\n"
            + "    FROM attendance_raw ar\r\n"
            + "\r\n"
            + "    GROUP BY\r\n"
            + "\r\n"
            + "        ar.empcode,\r\n"
            + "\r\n"
            + "        ar.checkindate\r\n"
            + "),\r\n"
            + "\r\n"
            + "\r\n"
            + "/* ============================================================\r\n"
            + "   5. ONLY OT ELIGIBLE EMPLOYEES\r\n"
            + "\r\n"
            + "   IMPORTANT:\r\n"
            + "\r\n"
            + "   otflag = 1 ONLY\r\n"
            + "\r\n"
            + "   otflag = 0 employees are completely excluded.\r\n"
            + "   ============================================================ */\r\n"
            + "\r\n"
            + "employee_ot AS\r\n"
            + "(\r\n"
            + "    SELECT\r\n"
            + "\r\n"
            + "        e.employeecode,\r\n"
            + "\r\n"
            + "        e.otflag\r\n"
            + "\r\n"
            + "    FROM employee e\r\n"
            + "\r\n"
            + "    WHERE\r\n"
            + "\r\n"
            + "        e.orgid = ?3 \r\n"
            + "\r\n"
            + "        AND e.otflag = 1\r\n"
            + "),\r\n"
            + "\r\n"
            + "\r\n"
            + "/* ============================================================\r\n"
            + "   6. ATTENDANCE + OT ELIGIBLE EMPLOYEE\r\n"
            + "   ============================================================ */\r\n"
            + "\r\n"
            + "daily_employee AS\r\n"
            + "(\r\n"
            + "    SELECT\r\n"
            + "\r\n"
            + "        da.employeecode,\r\n"
            + "\r\n"
            + "        da.employeename,\r\n"
            + "\r\n"
            + "        da.attendancedate,\r\n"
            + "\r\n"
            + "        da.first_in,\r\n"
            + "\r\n"
            + "        da.last_out,\r\n"
            + "\r\n"
            + "        da.actual_work_minutes,\r\n"
            + "\r\n"
            + "        eo.otflag AS employee_otflag\r\n"
            + "\r\n"
            + "    FROM daily_attendance da\r\n"
            + "\r\n"
            + "    INNER JOIN employee_ot eo\r\n"
            + "\r\n"
            + "        ON eo.employeecode =\r\n"
            + "           da.employeecode\r\n"
            + "),\r\n"
            + "\r\n"
            + "\r\n"
            + "/* ============================================================\r\n"
            + "   7. DAILY WORK CALCULATION\r\n"
            + "   ============================================================ */\r\n"
            + "\r\n"
            + "daily_work AS\r\n"
            + "(\r\n"
            + "    SELECT\r\n"
            + "\r\n"
            + "        de.employeecode,\r\n"
            + "\r\n"
            + "        de.employeename,\r\n"
            + "\r\n"
            + "        de.attendancedate,\r\n"
            + "\r\n"
            + "        de.first_in,\r\n"
            + "\r\n"
            + "        de.last_out,\r\n"
            + "\r\n"
            + "        de.actual_work_minutes,\r\n"
            + "\r\n"
            + "        de.employee_otflag,\r\n"
            + "\r\n"
            + "        cs.shifthours,\r\n"
            + "\r\n"
            + "        cs.oteligiblehours,\r\n"
            + "\r\n"
            + "        ROUND(\r\n"
            + "            cs.shifthours * 60\r\n"
            + "        ) AS shift_minutes,\r\n"
            + "\r\n"
            + "        ROUND(\r\n"
            + "            de.actual_work_minutes / 60,\r\n"
            + "            2\r\n"
            + "        ) AS actual_work_hours,\r\n"
            + "\r\n"
            + "        GREATEST(\r\n"
            + "\r\n"
            + "            de.actual_work_minutes\r\n"
            + "\r\n"
            + "            -\r\n"
            + "\r\n"
            + "            ROUND(\r\n"
            + "                cs.shifthours * 60\r\n"
            + "            ),\r\n"
            + "\r\n"
            + "            0\r\n"
            + "\r\n"
            + "        ) AS extra_work_minutes\r\n"
            + "\r\n"
            + "    FROM daily_employee de\r\n"
            + "\r\n"
            + "    CROSS JOIN company_settings cs\r\n"
            + "),\r\n"
            + "\r\n"
            + "\r\n"
            + "/* ============================================================\r\n"
            + "   8. DAILY OT CALCULATION\r\n"
            + "   ============================================================ */\r\n"
            + "\r\n"
            + "daily_ot AS\r\n"
            + "(\r\n"
            + "    SELECT\r\n"
            + "\r\n"
            + "        dw.employeecode,\r\n"
            + "\r\n"
            + "        dw.employeename,\r\n"
            + "\r\n"
            + "        dw.attendancedate,\r\n"
            + "\r\n"
            + "        dw.first_in,\r\n"
            + "\r\n"
            + "        dw.last_out,\r\n"
            + "\r\n"
            + "        dw.actual_work_minutes,\r\n"
            + "\r\n"
            + "        dw.employee_otflag,\r\n"
            + "\r\n"
            + "        dw.shifthours,\r\n"
            + "\r\n"
            + "        dw.oteligiblehours,\r\n"
            + "\r\n"
            + "        dw.actual_work_hours,\r\n"
            + "\r\n"
            + "\r\n"
            + "        /* =====================================================\r\n"
            + "           OT HOURS\r\n"
            + "           ===================================================== */\r\n"
            + "\r\n"
            + "        CASE\r\n"
            + "\r\n"
            + "            WHEN dw.extra_work_minutes >=\r\n"
            + "                 (\r\n"
            + "                     COALESCE(\r\n"
            + "                         dw.oteligiblehours,\r\n"
            + "                         0\r\n"
            + "                     ) * 60\r\n"
            + "                 )\r\n"
            + "\r\n"
            + "            THEN ROUND(\r\n"
            + "                dw.extra_work_minutes / 60,\r\n"
            + "                2\r\n"
            + "            )\r\n"
            + "\r\n"
            + "            ELSE 0\r\n"
            + "\r\n"
            + "        END AS ot_hours,\r\n"
            + "\r\n"
            + "\r\n"
            + "        /* =====================================================\r\n"
            + "           OT DAYS\r\n"
            + "           ===================================================== */\r\n"
            + "\r\n"
            + "        CASE\r\n"
            + "\r\n"
            + "            WHEN dw.extra_work_minutes >=\r\n"
            + "                 (\r\n"
            + "                     COALESCE(\r\n"
            + "                         dw.oteligiblehours,\r\n"
            + "                         0\r\n"
            + "                     ) * 60\r\n"
            + "                 )\r\n"
            + "\r\n"
            + "            THEN 1\r\n"
            + "\r\n"
            + "            ELSE 0\r\n"
            + "\r\n"
            + "        END AS ot_days\r\n"
            + "\r\n"
            + "    FROM daily_work dw\r\n"
            + "),\r\n"
            + "\r\n"
            + "\r\n"
            + "/* ============================================================\r\n"
            + "   9. EMPLOYEE PERIOD TOTAL\r\n"
            + "   ============================================================ */\r\n"
            + "\r\n"
            + "employee_monthly AS\r\n"
            + "(\r\n"
            + "    SELECT\r\n"
            + "\r\n"
            + "        employeecode,\r\n"
            + "\r\n"
            + "        MAX(\r\n"
            + "            employeename\r\n"
            + "        ) AS employeename,\r\n"
            + "\r\n"
            + "        MIN(\r\n"
            + "            first_in\r\n"
            + "        ) AS first_in,\r\n"
            + "\r\n"
            + "        MAX(\r\n"
            + "            last_out\r\n"
            + "        ) AS last_out,\r\n"
            + "\r\n"
            + "        COUNT(\r\n"
            + "            DISTINCT attendancedate\r\n"
            + "        ) AS present,\r\n"
            + "\r\n"
            + "        ROUND(\r\n"
            + "            SUM(\r\n"
            + "                shifthours\r\n"
            + "            ),\r\n"
            + "            2\r\n"
            + "        ) AS shift_hours,\r\n"
            + "\r\n"
            + "        ROUND(\r\n"
            + "            SUM(\r\n"
            + "                actual_work_minutes\r\n"
            + "            ) / 60,\r\n"
            + "            2\r\n"
            + "        ) AS actual_work_hours,\r\n"
            + "\r\n"
            + "        SUM(\r\n"
            + "            ot_days\r\n"
            + "        ) AS ot_days,\r\n"
            + "\r\n"
            + "        ROUND(\r\n"
            + "            SUM(\r\n"
            + "                ot_hours\r\n"
            + "            ),\r\n"
            + "            2\r\n"
            + "        ) AS ot_hours,\r\n"
            + "\r\n"
            + "        GROUP_CONCAT(\r\n"
            + "\r\n"
            + "            CASE\r\n"
            + "\r\n"
            + "                WHEN ot_days = 1\r\n"
            + "\r\n"
            + "                THEN DATE_FORMAT(\r\n"
            + "                    attendancedate,\r\n"
            + "                    '%Y-%m-%d'\r\n"
            + "                )\r\n"
            + "\r\n"
            + "                ELSE NULL\r\n"
            + "\r\n"
            + "            END\r\n"
            + "\r\n"
            + "            ORDER BY attendancedate\r\n"
            + "\r\n"
            + "            SEPARATOR ', '\r\n"
            + "\r\n"
            + "        ) AS ot_dates\r\n"
            + "\r\n"
            + "    FROM daily_ot\r\n"
            + "\r\n"
            + "    GROUP BY\r\n"
            + "\r\n"
            + "        employeecode\r\n"
            + ")\r\n"
            + "\r\n"
            + "\r\n"
            + "/* ============================================================\r\n"
            + "   10. FINAL RESULT\r\n"
            + "   ============================================================ */\r\n"
            + "\r\n"
            + "SELECT\r\n"
            + "\r\n"
            + "    ROW_NUMBER() OVER\r\n"
            + "    (\r\n"
            + "        ORDER BY\r\n"
            + "\r\n"
            + "            em.ot_days DESC,\r\n"
            + "\r\n"
            + "            em.employeecode ASC\r\n"
            + "\r\n"
            + "    ) AS `S.No`,\r\n"
            + "\r\n"
            + "    em.employeecode AS `Employee Code`,\r\n"
            + "\r\n"
            + "    em.employeename AS `Employee Name`,\r\n"
            + "\r\n"
            + "    DATE_FORMAT(\r\n"
            + "        em.first_in,\r\n"
            + "        '%Y-%m-%d %H:%i:%s'\r\n"
            + "    ) AS `First In`,\r\n"
            + "\r\n"
            + "    DATE_FORMAT(\r\n"
            + "        em.last_out,\r\n"
            + "        '%Y-%m-%d %H:%i:%s'\r\n"
            + "    ) AS `Last Out`,\r\n"
            + "\r\n"
            + "    DATEDIFF(\r\n"
            + "        rp.to_date,\r\n"
            + "        rp.from_date\r\n"
            + "    ) + 1 AS `Total Days`,\r\n"
            + "\r\n"
            + "    em.present AS `Present`,\r\n"
            + "\r\n"
            + "    ROUND(\r\n"
            + "        em.shift_hours,\r\n"
            + "        2\r\n"
            + "    ) AS `Shift Hours`,\r\n"
            + "\r\n"
            + "    ROUND(\r\n"
            + "        em.actual_work_hours,\r\n"
            + "        2\r\n"
            + "    ) AS `Actual Work Hours`,\r\n"
            + "\r\n"
            + "    em.ot_days AS `OT Days`,\r\n"
            + "\r\n"
            + "    ROUND(\r\n"
            + "        em.ot_hours,\r\n"
            + "        2\r\n"
            + "    ) AS `OT Hours`,\r\n"
            + "\r\n"
            + "    COALESCE(\r\n"
            + "        em.ot_dates,\r\n"
            + "        ''\r\n"
            + "    ) AS `OT Dates`,\r\n"
            + "\r\n"
            + "    CASE\r\n"
            + "\r\n"
            + "        WHEN em.ot_days > 0\r\n"
            + "\r\n"
            + "        THEN 'TRUE'\r\n"
            + "\r\n"
            + "        ELSE 'FALSE'\r\n"
            + "\r\n"
            + "    END AS `OT Status`\r\n"
            + "\r\n"
            + "FROM employee_monthly em\r\n"
            + "\r\n"
            + "CROSS JOIN report_period rp\r\n"
            + "WHERE em.ot_days > 0\r\n"
            + "\r\n"
            + "ORDER BY\r\n"
            + "\r\n"
            + "    em.ot_days DESC,\r\n"
            + "\r\n"
            + "    em.employeecode ASC",

        nativeQuery = true
    )
    List<Map<String, Object>> getOvertimeReport(
            @Param("fromDate") LocalDate fromDate,
            @Param("toDate") LocalDate toDate,
            @Param("orgId") Long orgId
    );





}
